### ISSUE TITLE
Don't enforce inline-start and inline-end for float values

### ISSUE THREAD

**Issue by felixranesberger** [csstools/stylelint-use-logical#17]
When using `float: left;` or `float: right;` Stylelint throws the following error:

```
Unexpected "left" value in "float" property. Use "inline-start".  csstools/use-logical
Unexpected "right" value in "float" property. Use "inline-end".   csstools/use-logical
```

This is an issue, because currently only Firefox supports `inline-start` and `inline-end` in combination with the float property.

See: https://developer.mozilla.org/en-US/docs/Web/CSS/float?retiredLocale=de#browser_compatibility

**Comment by romainmenke** [comment]
This is now supported by all browsers : https://developer.mozilla.org/en-US/docs/Web/CSS/float#browser_compatibility

And there is a PostCSS plugin to downgrade : https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-logical-float-and-clear

So I am going to close this since the purpose of this plugin is to promote the use of logical props and values.
Please let me know if I understood.

**Comment by felixranesberger** [comment]
Thanks for the update 🚀
